pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'node'
                }
            }
            steps {
                sh 'sh jenkins/staging/scripts/build.sh'
            }
        }
         stage('Deliver') {
            agent any
            steps {
                sh 'sh jenkins/staging/scripts/deliver.sh'
            }
        }
    }
}
